# typed: false
# frozen_string_literal: true

# This file was generated from the md-fixup repository.
# Do not edit this file directly. Instead, update the version and SHA256
# in this file when releasing a new version.

class MdFixup < Formula
  desc "Markdown linter that normalizes formatting and wraps text"
  homepage "https://github.com/ttscoff/md-fixup"
  license "MIT"
  head "https://github.com/ttscoff/md-fixup.git", branch: "main"

  # Binary distribution (faster installation)
  if OS.mac?
    if Hardware::CPU.intel?
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.27/md-fixup-x86_64-apple-darwin.tar.gz"
      sha256 "b2dd5f5ca108018ca2089d938b4d23d024f56575da98cf431af816d104526483"
    else
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.27/md-fixup-aarch64-apple-darwin.tar.gz"
      sha256 "12daa752e2057441cc9e89efc154578e4bdbc03ca67119226f015255cbf590bb"
    end
  else
    if Hardware::CPU.intel?
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.27/md-fixup-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "79b0cbf32a87ca7d60ccb716a203b6b940c63c89c8f7ae97d5f7d1c8286fe1ac"
    else
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.27/md-fixup-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e7412247ec9aa4fdea53cfe9984ff6ae176767cdbdd8e620d72a43f234141ecc"
    end
  end

  def install
    bin.install "md-fixup"
  end

  test do
    (testpath/"test.md").write "# Test\n\nSome text."
    system "#{bin}/md-fixup", "test.md"
    assert_match "# Test", File.read("test.md")
  end
end
