# typed: false
# frozen_string_literal: true

# This file was generated from the md-fixup repository.
# Do not edit this file directly. Instead, update the version and SHA256
# in this file when releasing a new version.

class MdFixup < Formula
  desc "Markdown linter that normalizes formatting and wraps text"
  homepage "https://github.com/ttscoff/md-fixup"
  license "MIT"
  head "https://github.com/ttscoff/md-fixup.git", branch: "main"

  # Binary distribution (faster installation)
  if OS.mac?
    if Hardware::CPU.intel?
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.26/md-fixup-x86_64-apple-darwin.tar.gz"
      sha256 "f1070984f01f8c651cd1efd483e82d53ce1cc0b609d1ca5c253ff3faa5635d0b"
    else
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.26/md-fixup-aarch64-apple-darwin.tar.gz"
      sha256 "a00a92df83ef0206e77383d32d2464615884de69553e8dc7b75af9e5dff58e34"
    end
  else
    if Hardware::CPU.intel?
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.26/md-fixup-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "e975bce37a8fac84256215eceda3ec19a22b488b21fd9664fce2add4d3044b6c"
    else
      url "https://github.com/ttscoff/md-fixup/releases/download/v0.1.26/md-fixup-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4578e27c06bbd3d17064ff153e4df377c403d154144690473af3d7b7e46fd665"
    end
  end

  def install
    bin.install "md-fixup"
  end

  test do
    (testpath/"test.md").write "# Test\n\nSome text."
    system "#{bin}/md-fixup", "test.md"
    assert_match "# Test", File.read("test.md")
  end
end
